version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - LOG_LEVEL=info
      - JWT_SECRET=${JWT_SECRET} # Pull from .env or host env
      - DATABASE_URL=${DATABASE_URL} # Neon DB URL
      - ARCJET_KEY=${ARCJET_KEY} # Arcjet key
    volumes:
      - ./logs:/app/logs # Mount logs directory for persistence
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:5000/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
