apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: purchase
  name: purchase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: purchase
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: purchase
    spec:
      containers:
        - image: rafiq9323/acquisitions-purchase
          name: acquisitions-purchase
          resources: {}
status: {}
