apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: purchase
  name: purchase
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: purchase
  type: NodePort
status:
  loadBalancer: {}
